---
apiVersion: v1
kind: Secret
metadata:
  name: rhug-backend-rhug-backend-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ultraJeffOrg/rhug-backend-backend-gitops
